### ISSUE TITLE
Joining Bots

### ISSUE THREAD

**Issue by stefanfx** [XuaTheGrate/Discord-Clusters#1]
I have tried your code and it is awesome. But the only thing I don't get is how can I make the clusters act as one as my bot uses cross-server messaging. I get two separate bots for 2 clusters and I noticed that my stats command displays only guilds and shard on the cluster the command was used. How can I make it to show the real guild cout and the clusters to use each others servers,cache etc.

**Comment by XuaTheGrate** [comment]
You would need to use an IPC server to communicate between the two bots.
There is an example one there, however anything past that you will need to try and figure out on your own.
