### ISSUE TITLE
How to add commands to the file exactly?

### ISSUE THREAD

**Issue by TestAccout1** [XuaTheGrate/Discord-Clusters#3]
If I understood the Read Me section correctly, I have to add the commands to the `bot.py` file, however, I can't seem to figure out how exactly can I add them and how can I set the prefix.

I know how to make commands and set prefixes normally, but I couldn't figure out how to add them to the `bot.py` file.

Please if you could add a little simple-response example command code for reference, it would be highly appreciated.

**Comment by XuaTheGrate** [comment]
Generally you don't want to add them into the main bot file, you'd be better off creating cogs for each bot to use. An example can be found, as well as a link to the official documentation.

https://gist.github.com/EvieePy/d78c061a4798ae81be9825468fe146be
https://discordpy.readthedocs.io/en/latest/ext/commands/cogs.html#ext-commands-cogs
